// ============================================================================
// Kangwifi APIs — Elysia + Bun edition
// ----------------------------------------------------------------------------
// Fork of kaminoa-api (Express) → ported to Elysia + Bun, then expanded with
// scrapers ported from r2-kana.vercel.app, and rebranded as "Kangwifi APIs".
//
// Auto-discovery contract: drop a file in `fitur/`, restart, and the endpoint
// is live. Each feature file exports `default { route, handler }` where
// `route` carries OpenAPI metadata (method, path, tags, summary, description,
// parameters, responses, auth) and `handler` is an Express-style
// `(req, res) => { ... }` function.
//
// Docs are auto-generated by @elysiajs/swagger, served at /swagger.
//
// Why this is fast:
//   1. Bun's native HTTP server (Zig + JavaScriptCore).
//   2. Elysia precompiles its route tree at registration time.
//   3. All 140+ feature files are imported in parallel at boot.
//   4. The swagger spec is generated once per host and cached.
//   5. Auth check is inlined into the route handler (no middleware indirection).
// ============================================================================

import { Elysia } from "elysia"
import { swagger } from "@elysiajs/swagger"
import { readdirSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath, pathToFileURL } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))

// ─── Config ──────────────────────────────────────────────────────────────────
// Bun auto-loads .env from the project root on boot.
const API_KEY = process.env.API_KEY
const PORT = Number(process.env.PORT) || 47291

if (!API_KEY) {
    console.warn("[auth] Peringatan: API_KEY belum di-set. Endpoint dengan auth: true akan menolak semua request.")
}

// ─── Walk fitur/ for .js files ───────────────────────────────────────────────
function walkDir(dir, out = []) {
    const entries = readdirSync(dir, { withFileTypes: true })
    for (const entry of entries) {
        const full = join(dir, entry.name)
        if (entry.isDirectory()) walkDir(full, out)
        else if (entry.name.endsWith(".js")) out.push(full)
    }
    return out
}

// ─── Parallel feature loading ────────────────────────────────────────────────
const featureFiles = walkDir(join(__dirname, "fitur"))
const features = []

await Promise.all(featureFiles.map(async (file) => {
    try {
        const mod = await import(pathToFileURL(file).href)
        const f = mod.default
        if (f?.route && typeof f.handler === "function") {
            features.push(f)
        } else {
            console.warn(`[skip] ${file}: tidak punya route/handler valid`)
        }
    } catch (e) {
        console.warn(`[warn] Gagal load ${file}:`, e.message)
    }
}))

features.sort((a, b) => a.route.path.localeCompare(b.route.path))
console.log(`[routes] ${features.length} endpoint loaded`)

// ─── Express-style → Elysia adapter ─────────────────────────────────────────
// Each feature file exports: `handler: async (req, res) => { ... }` where
// `req` looks like Express's req (req.query, req.headers) and `res` looks
// like Express's res (res.status(n).json({...}), res.json({...})).
//
// We synthesize a minimal req/res pair that maps to Elysia's context. This
// means zero changes needed in any of the 140+ feature files.
function adapt(feature) {
    const run = feature.handler
    return async (c) => {
        let status = 200
        let response = null

        const req = {
            query: c.query,
            headers: c.headers,
            get: (h) => c.headers[h.toLowerCase()],
        }

        const res = {
            status(code) { status = code; return this },
            json(obj) {
                response = new Response(JSON.stringify(obj), {
                    status,
                    headers: { "content-type": "application/json; charset=utf-8" },
                })
                return response
            },
            send(body) {
                const isBuf = Buffer.isBuffer(body)
                response = new Response(body, {
                    status,
                    headers: isBuf
                        ? { "content-type": "application/octet-stream" }
                        : { "content-type": "text/html; charset=utf-8" },
                })
                return response
            },
            end(body) {
                response = new Response(body ?? null, { status })
                return response
            },
        }

        try {
            await run(req, res)
            if (response) return response
            return new Response(null, { status })
        } catch (e) {
            return new Response(
                JSON.stringify({ ok: false, error: e?.message || String(e) }),
                { status: 500, headers: { "content-type": "application/json; charset=utf-8" } },
            )
        }
    }
}

// ─── Build the Elysia app ────────────────────────────────────────────────────
const app = new Elysia()

// ─── Swagger / OpenAPI docs ──────────────────────────────────────────────────
// The @elysiajs/swagger plugin auto-generates OpenAPI 3 docs from Elysia's
// route metadata. Each route we register can pass a `detail` object that
// controls how it appears in the docs (tags, summary, description, params,
// responses, security). We map our feature-file `route` metadata into
// Elysia's `detail` so the existing 140+ feature files work unchanged.
app.use(
    swagger({
        path: "/docs",
        documentation: {
            info: {
                title: "Kangwifi APIs",
                version: "1.0.0",
                description:
                    "Koleksi REST API by kangwifi. Dibangun di atas Elysia + Bun untuk performa maksimal. " +
                    "Endpoint asli kaminoa-api tetap utuh; tambahan endpoint `/kana/*` di-port dari r2-kana.vercel.app.",
            },
            components: {
                securitySchemes: {
                    ApiKeyAuth: {
                        type: "apiKey",
                        in: "header",
                        name: "x-api-key",
                    },
                },
            },
            tags: [
                { name: "AI", description: "Chat & text generation" },
                { name: "Downloader", description: "Media downloaders" },
                { name: "Search", description: "Search engines" },
                { name: "Tools", description: "Utility tools" },
                { name: "Maker", description: "Image / text makers" },
                { name: "Islamic", description: "Islamic utilities" },
                { name: "Kana · AI", description: "AI scrapers ported from r2-kana" },
                { name: "Kana · Downloader", description: "Downloaders ported from r2-kana" },
                { name: "Kana · Search", description: "Search scrapers ported from r2-kana" },
                { name: "Kana · Tools", description: "Utility tools ported from r2-kana" },
            ],
        },
    }),
)

// ─── Register every feature route ────────────────────────────────────────────
for (const f of features) {
    const {
        method, path: routePath, auth,
        tags = [], summary, description,
        parameters, requestBody, responses,
    } = f.route

    const verb = method.toLowerCase()
    if (typeof app[verb] !== "function") {
        console.warn(`[skip] unsupported HTTP method "${method}" for ${routePath}`)
        continue
    }

    const handler = adapt(f)

    // Map our route metadata into Elysia's `detail` (for swagger) and
    // `beforeHandle` (for auth check, inlined — no middleware indirection).
    const routeConfig = {
        detail: {
            tags,
            ...(summary && { summary }),
            ...(description && { description }),
            ...(parameters && { params: parameters.filter(p => p.in === "path") }),
            ...(parameters && { query: parameters.filter(p => p.in === "query") }),
            ...(responses && {
                response: Object.fromEntries(
                    Object.entries(responses).map(([code, r]) => [
                        code,
                        r?.content?.["application/json"]?.schema ?? {},
                    ]),
                ),
            }),
            ...(auth && { security: [{ ApiKeyAuth: [] }] }),
        },
        ...(auth && {
            beforeHandle: (c) => {
                const key = c.headers["x-api-key"]
                if (!key || key !== API_KEY) {
                    return new Response(
                        JSON.stringify({ ok: false, error: "API key tidak valid" }),
                        { status: 401, headers: { "content-type": "application/json; charset=utf-8" } },
                    )
                }
            },
        }),
    }

    app[verb](routePath, handler, routeConfig)
}

// ─── Root redirect ───────────────────────────────────────────────────────────
app.get("/", () => Response.redirect("/docs", 302))

// ─── 404 / 500 ───────────────────────────────────────────────────────────────
app.onError(({ code, error, path, set }) => {
    if (code === "NOT_FOUND") {
        set.status = 404
        return {
            ok: false,
            error: "Endpoint tidak ditemukan",
            path,
        }
    }
    set.status = 500
    return {
        ok: false,
        error: error?.message || String(error),
        code,
    }
})

// ─── Boot ────────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
    console.log("")
    console.log("  Kangwifi APIs  →  Elysia + Bun edition")
    console.log(`  Listen         →  http://localhost:${PORT}`)
    console.log(`  Docs (Swagger) →  http://localhost:${PORT}/docs`)
    console.log(`  Routes         →  ${features.length}`)
    console.log("")
})
