// ============================================================================
// Kangwifi APIs — Elysia + Bun edition (v2: POST + CORS + Easy-mode)
// ----------------------------------------------------------------------------
// REST API collection built on Elysia + Bun. Auto-discovery: drop a file in
// `fitur/`, restart, and the endpoint is live. Each feature file exports
// `default { route, handler }` where `route` carries OpenAPI metadata
// (method, path, tags, summary, description, parameters, responses, auth)
// and `handler` is an Express-style `(req, res) => { ... }` function.
//
// v2 IMPROVEMENTS:
//   - Every GET endpoint now also accepts POST with JSON body
//   - req.query auto-merges JSON body params (body overrides query)
//   - CORS headers added (Access-Control-Allow-Origin: *)
//   - Root "/" returns a simple usage guide (not just redirect to /docs)
//   - Better mobile/Hoppscotch UX — POST with {"prompt": "..."} is way easier
//
// Docs are auto-generated by @elysiajs/swagger, served at /docs. The Scalar
// UI bundle is self-hosted at /scalar.js so the docs work without internet.
// ============================================================================

import { Elysia } from "elysia"
import { swagger } from "@elysiajs/swagger"
import { readdirSync, readFileSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath, pathToFileURL } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))

// ─── Config ──────────────────────────────────────────────────────────────────
const ENABLE_AUTH = process.env.ENABLE_AUTH === "true"
const API_KEY = process.env.API_KEY
const PORT = Number(process.env.PORT) || 47291

if (ENABLE_AUTH && !API_KEY) {
    console.warn("[auth] ENABLE_AUTH=true tapi API_KEY belum di-set. Endpoint auth: true akan menolak semua request.")
}
if (!ENABLE_AUTH) {
    console.log("[auth] Auth dinonaktifkan — semua endpoint terbuka tanpa API key.")
}

// ─── Walk fitur/ for .js files ───────────────────────────────────────────────
function walkDir(dir, out = []) {
    const entries = readdirSync(dir, { withFileTypes: true })
    for (const entry of entries) {
        const full = join(dir, entry.name)
        if (entry.isDirectory()) walkDir(full, out)
        else if (entry.name.endsWith(".js")) out.push(full)
    }
    return out
}

// ─── Parallel feature loading ────────────────────────────────────────────────
const featureFiles = walkDir(join(__dirname, "fitur"))
const features = []

await Promise.all(featureFiles.map(async (file) => {
    try {
        const mod = await import(pathToFileURL(file).href)
        const f = mod.default
        if (f?.route && typeof f.handler === "function") {
            features.push(f)
        } else {
            console.warn(`[skip] ${file}: tidak punya route/handler valid`)
        }
    } catch (e) {
        console.warn(`[warn] Gagal load ${file}:`, e.message)
    }
}))

features.sort((a, b) => a.route.path.localeCompare(b.route.path))
console.log(`[routes] ${features.length} endpoint loaded`)

// ─── Express-style → Elysia adapter (v2: POST + body support) ────────────────
// Key change: req.query now auto-merges c.body (JSON) on POST requests.
// This means ALL 140+ existing handlers work unchanged for BOTH GET and POST.
// On POST, body params override query params with the same name.
function adapt(feature) {
    const run = feature.handler
    return async (c) => {
        let status = 200
        let response = null

        // Merge query + body into a single req.query.
        // On GET: req.query = c.query only (no body).
        // On POST: req.query = { ...c.query, ...c.body } — body overrides query.
        // This way, handlers that read from req.query work for both GET and POST.
        const body = (c.body && typeof c.body === "object" && !Buffer.isBuffer(c.body)) ? c.body : {}
        const mergedQuery = { ...c.query, ...body }

        const req = {
            query: mergedQuery,
            body: body,
            headers: c.headers,
            get: (h) => c.headers[h.toLowerCase()],
        }

        const res = {
            status(code) { status = code; return this },
            json(obj) {
                response = new Response(JSON.stringify(obj), {
                    status,
                    headers: {
                        "content-type": "application/json; charset=utf-8",
                        "access-control-allow-origin": "*",
                    },
                })
                return response
            },
            send(body) {
                const isBuf = Buffer.isBuffer(body)
                response = new Response(body, {
                    status,
                    headers: {
                        ...(isBuf
                            ? { "content-type": "application/octet-stream" }
                            : { "content-type": "text/html; charset=utf-8" }),
                        "access-control-allow-origin": "*",
                    },
                })
                return response
            },
            end(body) {
                response = new Response(body ?? null, {
                    status,
                    headers: { "access-control-allow-origin": "*" },
                })
                return response
            },
        }

        try {
            await run(req, res)
            if (response) return response
            return new Response(null, { status, headers: { "access-control-allow-origin": "*" } })
        } catch (e) {
            return new Response(
                JSON.stringify({ ok: false, error: e?.message || String(e) }),
                { status: 500, headers: { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "*" } },
            )
        }
    }
}

// ─── Build the Elysia app ────────────────────────────────────────────────────
const app = new Elysia()

// ─── CORS: Allow all origins (mobile apps, web apps, Hoppscotch, etc) ────────
app.onRequest(({ set }) => {
    set.headers["access-control-allow-origin"] = "*"
    set.headers["access-control-allow-methods"] = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    set.headers["access-control-allow-headers"] = "Content-Type, x-api-key, Authorization, Accept, Origin"
})

// Handle CORS preflight (OPTIONS) for all paths
app.options("*", ({ set }) => {
    set.status = 204
    set.headers["access-control-allow-origin"] = "*"
    set.headers["access-control-allow-methods"] = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    set.headers["access-control-allow-headers"] = "Content-Type, x-api-key, Authorization, Accept, Origin"
    set.headers["access-control-max-age"] = "86400"
    return ""
})

// ─── Self-hosted Scalar bundle ───────────────────────────────────────────────
const SCALAR_BUNDLE_PATH = join(__dirname, "public", "scalar.js")
let scalarBundle = null
try {
    scalarBundle = readFileSync(SCALAR_BUNDLE_PATH, "utf-8")
    console.log(`[docs] Scalar bundle loaded locally (${(scalarBundle.length / 1024 / 1024).toFixed(2)} MB)`)
} catch (e) {
    console.warn(`[docs] WARNING: public/scalar.js not found — docs will try to load from CDN. Run: curl -o public/scalar.js https://cdn.jsdelivr.net/npm/@scalar/api-reference@latest/dist/browser/standalone.min.js`)
}

app.get("/scalar.js", () => {
    if (!scalarBundle) {
        return new Response("// Scalar bundle not found. See server logs.", {
            status: 404,
            headers: { "content-type": "application/javascript; charset=utf-8" },
        })
    }
    return new Response(scalarBundle, {
        headers: {
            "content-type": "application/javascript; charset=utf-8",
            "cache-control": "public, max-age=86400",
            "access-control-allow-origin": "*",
        },
    })
})

// ─── Swagger / OpenAPI docs ──────────────────────────────────────────────────
app.use(
    swagger({
        path: "/docs",
        provider: "scalar",
        scalarVersion: "latest",
        scalarCDN: scalarBundle ? "/scalar.js" : "",
        scalarConfig: {
            theme: "purple",
            layout: "modern",
            darkMode: true,
            showSidebar: true,
            hideSearch: false,
            hideModels: true,
            hideDownloadButton: false,
            hideTestRequestButton: false,
            defaultOpenAllTags: false,
            tagsSorter: "alpha",
            defaultHttpClient: {
                targetKey: "node",
                clientKey: "fetch",
            },
            hiddenClients: {
                shell: true,
                c: true,
                objc: true,
                swift: true,
                kotlin: true,
                dart: true,
                r: true,
                rust: true,
                ocaml: true,
                node: ["axios", "request", "unirest", "native", "jquery"],
            },
            metaData: {
                title: "Kangwifi APIs — Documentation",
                description: "REST API collection with 142 endpoints. Built on Elysia + Bun. Free, no API key required. Support GET + POST!",
                ogTitle: "Kangwifi APIs",
                ogDescription: "REST API collection with 142 endpoints. Built on Elysia + Bun. Support GET + POST!",
                ogImage: "https://opengraph.githubassets.com/1/Yz776/apis",
                twitterCard: "summary_large_image",
                twitterTitle: "Kangwifi APIs",
                twitterDescription: "REST API collection with 142 endpoints.",
            },
        },
        documentation: {
            info: {
                title: "Kangwifi APIs",
                version: "2.0.0",
                description: `# Kangwifi APIs v2

Koleksi **142 REST API endpoint** yang siap pakai, gratis, tanpa API key.

## Kenapa Pakai API Ini?

- **Super cepat** — Dibangun di atas **Bun + Elysia**, response time sub-millisecond
- **Gratis & tanpa API key** — Langsung pakai, tidak perlu registrasi
- **142 endpoint** — AI, downloader, search, tools, Islamic, dan banyak lagi
- **Mudah dipakai** — Support **GET** (query params) dan **POST** (JSON body)

## Cara Pakai — 2 Metode

### Metode 1: GET (untuk testing cepat)
Kirim parameter langsung di URL query string:

\`\`\`bash
curl "http://localhost:47291/ai/chatdeep?prompt=halo"
\`\`\`

### Metode 2: POST (RECOMMENDED — lebih mudah di HP / Hoppscotch)
Kirim parameter sebagai JSON body — **lebih gampang di mobile**:

\`\`\`bash
curl -X POST "http://localhost:47291/ai/chatdeep" \
  -H "Content-Type: application/json" \
  -d '{"prompt": "halo"}'
\`\`\`

\`\`\`javascript
// JavaScript fetch
const res = await fetch("http://localhost:47291/ai/chatdeep", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({ prompt: "halo" })
})
const data = await res.json()
\`\`\`

**POST lebih mudah karena:**
- Tidak perlu encode parameter di URL
- Bisa kirim prompt panjang tanpa masalah
- Format JSON lebih rapi dan gampang dibaca
- Langsung isi body di Hoppscotch / Postman tanpa ribet

## Contoh Cepat (POST)

\`\`\`bash
# Chat dengan DeepSeek AI
curl -X POST "http://localhost:47291/ai/chatdeep" \
  -H "Content-Type: application/json" \
  -d '{"prompt": "Apa itu lubang hitam?"}'

# Chat dengan Gemini AI
curl -X POST "http://localhost:47291/ai/gemini" \
  -H "Content-Type: application/json" \
  -d '{"prompt": "Siapa penemu telepon?"}'

# Chat dengan ChatGPT
curl -X POST "http://localhost:47291/ai/chatgpt" \
  -H "Content-Type: application/json" \
  -d '{"prompt": "Halo, kamu siapa?"}'

# Chat dengan Mistral AI
curl -X POST "http://localhost:47291/ai/mistral" \
  -H "Content-Type: application/json" \
  -d '{"prompt": "Apa itu artificial intelligence?"}'

# Download TikTok video
curl -X POST "http://localhost:47291/downloader/tiktokio" \
  -H "Content-Type: application/json" \
  -d '{"url": "https://vm.tiktok.com/xxx"}'

# Cari di Wikipedia
curl -X POST "http://localhost:47291/search/wikipedia" \
  -H "Content-Type: application/json" \
  -d '{"query": "indonesia"}'

# BMKG data gempa terkini (tanpa parameter)
curl "http://localhost:47291/tools/gempa"

# Jadwal sholat Jakarta
curl -X POST "http://localhost:47291/islamic/jadwal-sholat" \
  -H "Content-Type: application/json" \
  -d '{"kota": "Jakarta"}'
\`\`\`

## Kategori Endpoint

| Tag | Jumlah | Contoh |
|-----|--------|--------|
| **AI** | 17 | \`/ai/gemini\`, \`/ai/chatgpt\`, \`/ai/chatdeep\`, \`/ai/mistral\`, \`/ai/qwen\` |
| **Downloader** | 49 | \`/downloader/tiktokio\`, \`/downloader/savetube\`, \`/downloader/instagram\` |
| **Search** | 26 | \`/search/wikipedia\`, \`/search/kbbi\`, \`/search/pinterest\` |
| **Tools** | 47 | \`/tools/qrcode\`, \`/tools/tts\`, \`/tools/shorturl\` |
| **Maker** | 4 | \`/maker/brat\`, \`/maker/qc\` |
| **Islamic** | 6 | \`/islamic/quran-list\`, \`/islamic/jadwal-sholat\` |

## Autentikasi

**Tidak perlu API key!** Semua endpoint terbuka untuk umum secara default.

## Format Response

Semua endpoint mengembalikan JSON:

\`\`\`json
{
  "ok": true,
  "result": { ... },
  "text": "...",
  "error": "..." // hanya saat ok=false
}
\`\`\`

## Stack Teknis

- **Runtime**: [Bun 1.3+](https://bun.sh/)
- **Framework**: [ElysiaJS](https://elysiajs.com/)
- **Docs**: [@elysiajs/swagger](https://elysiajs.com/plugins/swagger) (Scalar UI)
- **Source**: [github.com/Yz776/apis](https://github.com/Yz776/apis)`,
            },
            components: {
                securitySchemes: {
                    ApiKeyAuth: {
                        type: "apiKey",
                        in: "header",
                        name: "x-api-key",
                    },
                },
            },
            tags: [
                {
                    name: "AI",
                    description: "Chat & text generation — Gemini, ChatGPT, Mistral, Qwen, DeepSeek, dll. Kirim prompt via GET (query) atau POST (JSON body).",
                },
                {
                    name: "Downloader",
                    description: "Media downloaders — TikTok, Instagram, YouTube, Spotify, dll. Kirim URL via GET (query) atau POST (JSON body).",
                },
                {
                    name: "Search",
                    description: "Search engines — Wikipedia, KBBI, Tokopedia, Pinterest, dll.",
                },
                {
                    name: "Tools",
                    description: "Utility tools — QR code, TTS, URL shortener, weather, gempa, translate, dll.",
                },
                {
                    name: "Maker",
                    description: "Image & text makers — brat generator, quote card, IQC.",
                },
                {
                    name: "Islamic",
                    description: "Islamic utilities — Quran, jadwal sholat, asmaul husna, doa harian, hadits.",
                },
            ],
        },
    }),
)

// ─── Register every feature route (GET + POST auto-registration) ─────────────
// v2 change: For every GET endpoint, we also register a POST version.
// This means ALL endpoints accept both GET (query params) and POST (JSON body).
// The adapt() function merges body into req.query, so handlers work unchanged.
for (const f of features) {
    const {
        method, path: routePath, auth,
        tags = [], summary, description,
        parameters, requestBody, responses,
    } = f.route

    const verb = method.toLowerCase()
    if (typeof app[verb] !== "function") {
        console.warn(`[skip] unsupported HTTP method "${method}" for ${routePath}`)
        continue
    }

    const handler = adapt(f)
    const enforceAuth = ENABLE_AUTH && auth

    // Build OpenAPI detail from the feature file metadata
    const buildDetail = (forPost = false) => {
        const detail = {
            tags,
            ...(summary && { summary: forPost ? `${summary} (POST)` : summary }),
            ...(description && { description }),
            ...(enforceAuth && { security: [{ ApiKeyAuth: [] }] }),
        }

        if (!forPost && parameters) {
            detail.params = parameters.filter(p => p.in === "path")
            detail.query = parameters.filter(p => p.in === "query")
        }

        if (forPost && parameters) {
            // For POST, build a requestBody schema from the query parameters
            const queryParams = parameters.filter(p => p.in === "query")
            if (queryParams.length > 0) {
                const properties = {}
                const required = []
                for (const p of queryParams) {
                    properties[p.name] = {
                        ...(p.schema || { type: "string" }),
                        ...(p.description && { description: p.description }),
                    }
                    if (p.required) required.push(p.name)
                }
                detail.body = {
                    type: "object",
                    properties,
                    ...(required.length > 0 && { required }),
                }
            }
        }

        if (forPost && requestBody) {
            detail.body = requestBody
        }

        if (responses) {
            detail.response = Object.fromEntries(
                Object.entries(responses).map(([code, r]) => [
                    code,
                    r?.content?.["application/json"]?.schema ?? {},
                ]),
            )
        }

        return detail
    }

    // Register the original method (usually GET)
    app[verb](routePath, handler, {
        detail: buildDetail(false),
        ...(enforceAuth && {
            beforeHandle: (c) => {
                const key = c.headers["x-api-key"]
                if (!key || key !== API_KEY) {
                    return new Response(
                        JSON.stringify({ ok: false, error: "API key tidak valid" }),
                        { status: 401, headers: { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "*" } },
                    )
                }
            },
        }),
    })

    // Auto-register POST for every GET endpoint
    if (verb === "get") {
        app.post(routePath, handler, {
            detail: buildDetail(true),
            ...(enforceAuth && {
                beforeHandle: (c) => {
                    const key = c.headers["x-api-key"]
                    if (!key || key !== API_KEY) {
                        return new Response(
                            JSON.stringify({ ok: false, error: "API key tidak valid" }),
                            { status: 401, headers: { "content-type": "application/json; charset=utf-8", "access-control-allow-origin": "*" } },
                        )
                    }
                },
            }),
        })
        console.log(`  [dual] ${routePath} → GET + POST`)
    }
}

// ─── Root "/" — Simple usage guide (mobile-friendly) ─────────────────────────
app.get("/", () => {
    const html = `<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Kangwifi APIs</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box }
body { background: #1a1a2e; color: #e0e0e0; font-family: system-ui, -apple-system, sans-serif; padding: 20px; min-height: 100vh }
.container { max-width: 800px; margin: auto }
h1 { color: #9b59b6; font-size: 2em; margin-bottom: 10px; text-align: center }
.subtitle { text-align: center; color: #888; margin-bottom: 30px; font-size: 1.1em }
.card { background: #16213e; border-radius: 12px; padding: 20px; margin-bottom: 15px; border: 1px solid #0f3460 }
.card h2 { color: #e94560; margin-bottom: 10px; font-size: 1.3em }
.card p { line-height: 1.6; margin-bottom: 8px }
.card code { background: #0f3460; padding: 2px 8px; border-radius: 4px; font-size: 0.9em; color: #53d769 }
.method-badge { display: inline-block; padding: 2px 10px; border-radius: 4px; font-size: 0.8em; font-weight: bold; margin-right: 6px }
.method-get { background: #27ae60; color: white }
.method-post { background: #e94560; color: white }
.btn { display: inline-block; background: #9b59b6; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: bold; margin: 10px 5px; text-align: center }
.btn:hover { background: #8e44ad }
pre { background: #0f3460; padding: 15px; border-radius: 8px; overflow-x: auto; font-size: 0.85em; line-height: 1.5; margin: 10px 0 }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 10px; margin-top: 15px }
.grid-item { background: #0f3460; padding: 10px; border-radius: 8px; text-align: center }
.grid-item a { color: #53d769; text-decoration: none; font-size: 0.9em }
.grid-item a:hover { color: #e94560 }
.highlight { color: #53d769; font-weight: bold }
</style>
</head>
<body>
<div class="container">
<h1>Kangwifi APIs v2</h1>
<p class="subtitle">142 endpoint — Gratis, tanpa API key — Support GET + POST</p>

<div class="card">
<h2>Cara Pakai</h2>
<p>Setiap endpoint support <span class="method-badge method-get">GET</span> dan <span class="method-badge method-post">POST</span>:</p>
<p><span class="method-badge method-get">GET</span> — Parameter di URL query string (untuk testing cepat)</p>
<p><span class="method-badge method-post">POST</span> — Parameter di JSON body (RECOMMENDED, lebih mudah di HP)</p>
</div>

<div class="card">
<h2>Contoh: Chat DeepSeek AI</h2>
<p><span class="method-badge method-get">GET</span> — Testing cepat:</p>
<pre>curl "http://localhost:${PORT}/ai/chatdeep?prompt=halo"</pre>

<p><span class="method-badge method-post">POST</span> — <span class="highlight">RECOMMENDED</span> (lebih mudah di Hoppscotch/HP):</p>
<pre>curl -X POST "http://localhost:${PORT}/ai/chatdeep" \\
  -H "Content-Type: application/json" \\
  -d '{"prompt": "halo"}'</pre>

<p>Di <strong>Hoppscotch / Postman</strong>: pilih method <span class="method-badge method-post">POST</span>, set Content-Type ke <code>application/json</code>, lalu isi body:</p>
<pre>{
  "prompt": "halo"
}</pre>
</div>

<div class="card">
<h2>Contoh: AI Endpoints (POST)</h2>
<pre># Gemini AI
curl -X POST "http://localhost:${PORT}/ai/gemini" \\
  -H "Content-Type: application/json" \\
  -d '{"prompt": "Siapa penemu telepon?"}'

# ChatGPT
curl -X POST "http://localhost:${PORT}/ai/chatgpt" \\
  -H "Content-Type: application/json" \\
  -d '{"prompt": "Halo, kamu siapa?"}'

# Mistral AI
curl -X POST "http://localhost:${PORT}/ai/mistral" \\
  -H "Content-Type: application/json" \\
  -d '{"prompt": "Apa itu AI?"}'

# DeepSeek (with thinking)
curl -X POST "http://localhost:${PORT}/ai/chatdeep" \\
  -H "Content-Type: application/json" \\
  -d '{"prompt": "Apa itu lubang hitam?", "thinking": true}'

# Qwen
curl -X POST "http://localhost:${PORT}/ai/qwen" \\
  -H "Content-Type: application/json" \\
  -d '{"prompt": "Jelaskan relativitas", "model": "qwen3.7-plus"}'

# Pollinations
curl -X POST "http://localhost:${PORT}/ai/pollinations" \\
  -H "Content-Type: application/json" \\
  -d '{"prompt": "Apa itu fotosintesis?"}'</pre>
</div>

<div class="card">
<h2>Contoh: Downloader (POST)</h2>
<pre># TikTok
curl -X POST "http://localhost:${PORT}/downloader/tiktokio" \\
  -H "Content-Type: application/json" \\
  -d '{"url": "https://vm.tiktok.com/xxx"}'

# Instagram
curl -X POST "http://localhost:${PORT}/downloader/instagram" \\
  -H "Content-Type: application/json" \\
  -d '{"url": "https://www.instagram.com/p/xxx"}'</pre>
</div>

<div class="card">
<h2>Kategori Endpoint</h2>
<div class="grid">
<div class="grid-item"><a href="/docs?tags=AI">🤖 AI (17)</a></div>
<div class="grid-item"><a href="/docs?tags=Downloader">⬇️ Downloader (49)</a></div>
<div class="grid-item"><a href="/docs?tags=Search">🔍 Search (26)</a></div>
<div class="grid-item"><a href="/docs?tags=Tools">🛠️ Tools (47)</a></div>
<div class="grid-item"><a href="/docs?tags=Maker">🎨 Maker (4)</a></div>
<div class="grid-item"><a href="/docs?tags=Islamic">🕌 Islamic (6)</a></div>
</div>
</div>

<div style="text-align:center; margin-top:20px">
<a class="btn" href="/docs">Buka Dokumentasi Lengkap</a>
<a class="btn" href="/docs/json">Download OpenAPI Spec</a>
</div>
</div>
</body>
</html>`
    return new Response(html, {
        headers: { "content-type": "text/html; charset=utf-8", "access-control-allow-origin": "*" },
    })
})

// ─── 404 / 500 ───────────────────────────────────────────────────────────────
app.onError(({ code, error, path, set }) => {
    set.headers["access-control-allow-origin"] = "*"
    if (code === "NOT_FOUND") {
        set.status = 404
        return {
            ok: false,
            error: "Endpoint tidak ditemukan",
            hint: `Coba buka /docs untuk lihat semua endpoint, atau POST ke endpoint yang benar.`,
            path,
        }
    }
    set.status = 500
    return {
        ok: false,
        error: error?.message || String(error),
        code,
    }
})

// ─── Boot ────────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
    console.log("")
    console.log("  Kangwifi APIs  →  Elysia + Bun edition (v2: POST + CORS)")
    console.log(`  Listen         →  http://localhost:${PORT}`)
    console.log(`  Docs (Swagger) →  http://localhost:${PORT}/docs`)
    console.log(`  Routes         →  ${features.length} endpoint (GET + POST = ${features.length * 2} total)`)
    console.log("")
})
