// ============================================================================
// Kangwifi APIs — Elysia + Bun edition
// ----------------------------------------------------------------------------
// REST API collection built on Elysia + Bun. Auto-discovery: drop a file in
// `fitur/`, restart, and the endpoint is live. Each feature file exports
// `default { route, handler }` where `route` carries OpenAPI metadata
// (method, path, tags, summary, description, parameters, responses, auth)
// and `handler` is an Express-style `(req, res) => { ... }` function.
//
// Docs are auto-generated by @elysiajs/swagger, served at /docs. The Scalar
// UI bundle is self-hosted at /scalar.js so the docs work without internet.
//
// Why this is fast:
//   1. Bun's native HTTP server (Zig + JavaScriptCore).
//   2. Elysia precompiles its route tree at registration time.
//   3. All 140+ feature files are imported in parallel at boot.
//   4. The swagger spec is generated once per host and cached.
//   5. Auth check is inlined into the route handler (no middleware indirection).
// ============================================================================

import { Elysia } from "elysia"
import { swagger } from "@elysiajs/swagger"
import { readdirSync, readFileSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath, pathToFileURL } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))

// ─── Config ──────────────────────────────────────────────────────────────────
// Bun auto-loads .env from the project root on boot.
//
// AUTH MODE: All endpoints are open by default — no API key required.
// The `auth` flag on individual feature files is IGNORED, so even endpoints
// originally marked `auth: true` are publicly accessible. If you later want
// to enforce auth, set ENABLE_AUTH=true in .env and provide API_KEY.
const ENABLE_AUTH = process.env.ENABLE_AUTH === "true"
const API_KEY = process.env.API_KEY
const PORT = Number(process.env.PORT) || 47291

if (ENABLE_AUTH && !API_KEY) {
    console.warn("[auth] ENABLE_AUTH=true tapi API_KEY belum di-set. Endpoint auth: true akan menolak semua request.")
}
if (!ENABLE_AUTH) {
    console.log("[auth] Auth dinonaktifkan — semua endpoint terbuka tanpa API key.")
}

// ─── Walk fitur/ for .js files ───────────────────────────────────────────────
function walkDir(dir, out = []) {
    const entries = readdirSync(dir, { withFileTypes: true })
    for (const entry of entries) {
        const full = join(dir, entry.name)
        if (entry.isDirectory()) walkDir(full, out)
        else if (entry.name.endsWith(".js")) out.push(full)
    }
    return out
}

// ─── Parallel feature loading ────────────────────────────────────────────────
const featureFiles = walkDir(join(__dirname, "fitur"))
const features = []

await Promise.all(featureFiles.map(async (file) => {
    try {
        const mod = await import(pathToFileURL(file).href)
        const f = mod.default
        if (f?.route && typeof f.handler === "function") {
            features.push(f)
        } else {
            console.warn(`[skip] ${file}: tidak punya route/handler valid`)
        }
    } catch (e) {
        console.warn(`[warn] Gagal load ${file}:`, e.message)
    }
}))

features.sort((a, b) => a.route.path.localeCompare(b.route.path))
console.log(`[routes] ${features.length} endpoint loaded`)

// ─── Express-style → Elysia adapter ─────────────────────────────────────────
// Each feature file exports: `handler: async (req, res) => { ... }` where
// `req` looks like Express's req (req.query, req.headers) and `res` looks
// like Express's res (res.status(n).json({...}), res.json({...})).
//
// We synthesize a minimal req/res pair that maps to Elysia's context. This
// means zero changes needed in any of the 140+ feature files.
function adapt(feature) {
    const run = feature.handler
    return async (c) => {
        let status = 200
        let response = null

        const req = {
            query: c.query,
            headers: c.headers,
            get: (h) => c.headers[h.toLowerCase()],
        }

        const res = {
            status(code) { status = code; return this },
            json(obj) {
                response = new Response(JSON.stringify(obj), {
                    status,
                    headers: { "content-type": "application/json; charset=utf-8" },
                })
                return response
            },
            send(body) {
                const isBuf = Buffer.isBuffer(body)
                response = new Response(body, {
                    status,
                    headers: isBuf
                        ? { "content-type": "application/octet-stream" }
                        : { "content-type": "text/html; charset=utf-8" },
                })
                return response
            },
            end(body) {
                response = new Response(body ?? null, { status })
                return response
            },
        }

        try {
            await run(req, res)
            if (response) return response
            return new Response(null, { status })
        } catch (e) {
            return new Response(
                JSON.stringify({ ok: false, error: e?.message || String(e) }),
                { status: 500, headers: { "content-type": "application/json; charset=utf-8" } },
            )
        }
    }
}

// ─── Build the Elysia app ────────────────────────────────────────────────────
const app = new Elysia()

// ─── Self-hosted Scalar bundle ───────────────────────────────────────────────
// The @elysiajs/swagger plugin normally loads the Scalar UI JavaScript from
// cdn.jsdelivr.net. In environments without internet access (containers, air-
// gapped servers), this causes the /docs page to render blank.
//
// To fix this, we ship the Scalar standalone bundle as a local file and serve
// it at /scalar.js. The swagger plugin's `scalarCDN` option points to this
// local URL so the docs load entirely from the server itself.
const SCALAR_BUNDLE_PATH = join(__dirname, "public", "scalar.js")
let scalarBundle = null
try {
    scalarBundle = readFileSync(SCALAR_BUNDLE_PATH, "utf-8")
    console.log(`[docs] Scalar bundle loaded locally (${(scalarBundle.length / 1024 / 1024).toFixed(2)} MB)`)
} catch (e) {
    console.warn(`[docs] WARNING: public/scalar.js not found — docs will try to load from CDN. Run: curl -o public/scalar.js https://cdn.jsdelivr.net/npm/@scalar/api-reference@latest/dist/browser/standalone.min.js`)
}

// Serve the Scalar bundle at /scalar.js with the correct content-type
app.get("/scalar.js", () => {
    if (!scalarBundle) {
        return new Response("// Scalar bundle not found. See server logs.", {
            status: 404,
            headers: { "content-type": "application/javascript; charset=utf-8" },
        })
    }
    return new Response(scalarBundle, {
        headers: {
            "content-type": "application/javascript; charset=utf-8",
            "cache-control": "public, max-age=86400",
        },
    })
})

// ─── Swagger / OpenAPI docs ──────────────────────────────────────────────────
// The @elysiajs/swagger plugin auto-generates OpenAPI 3 docs from Elysia's
// route metadata. Each route we register can pass a `detail` object that
// controls how it appears in the docs (tags, summary, description, params,
// responses, security). We map our feature-file `route` metadata into
// Elysia's `detail` so the existing 140+ feature files work unchanged.
//
// BEGINNER-FRIENDLY DOCS:
// We use the Scalar provider with the "purple" theme (easy on the eyes),
// modern layout, dark mode by default, hidden model schemas (overwhelming
// for beginners), and a curated set of HTTP clients (curl, fetch, JS, Python,
// Go) instead of showing all 20+ clients. We also embed a Markdown intro
// in the info.description so newcomers see examples + how-to-use right in
// the docs header.
app.use(
    swagger({
        path: "/docs",
        // Use Scalar (default) — much nicer than Swagger UI
        provider: "scalar",
        // Pin to a stable Scalar version
        scalarVersion: "latest",
        // Self-host the Scalar bundle — avoids CDN dependency (fixes blank
        // page in containers/air-gapped environments)
        scalarCDN: scalarBundle ? "/scalar.js" : "",
        scalarConfig: {
            // Visual theme — purple is high-contrast and beginner-friendly
            theme: "purple",
            // Modern layout: sidebar + main content (cleaner than classic)
            layout: "modern",
            // Start in dark mode (most developers prefer it; toggle is still visible)
            darkMode: true,
            // Show sidebar (with search + tag list)
            showSidebar: true,
            // Show the search bar in the sidebar (super useful with 142 endpoints)
            hideSearch: false,
            // Hide "Models" section — overwhelming for beginners, they just
            // want to see endpoints and try them
            hideModels: true,
            // Show "Download OpenAPI Document" button (for Postman/Insomnia import)
            hideDownloadButton: false,
            // Show "Test Request" button (Try-it-out) — key for beginners
            hideTestRequestButton: false,
            // Open all tags by default? No — with 6 tags and 142 endpoints it'd
            // be overwhelming. User clicks a tag to expand it.
            defaultOpenAllTags: false,
            // Sort tags alphabetically for predictable navigation
            tagsSorter: "alpha",
            // Default HTTP client: curl (most universal, easy to copy-paste)
            defaultHttpClient: {
                targetKey: "node",
                clientKey: "fetch",
            },
            // Hide obscure HTTP clients to reduce cognitive load
            // Keep only: curl, fetch (JS), python, go, php, java, csharp, ruby
            hiddenClients: {
                // Hide shell variants (wget, httpie) — curl is enough
                shell: true,
                // Hide C, ObjC, Swift, Kotlin, Dart, R, Rust, OCaml, etc.
                c: true,
                objc: true,
                swift: true,
                kotlin: true,
                dart: true,
                r: true,
                rust: true,
                ocaml: true,
                // Hide node variants (axios, request, unirest, native, jquery)
                // — keep only fetch
                node: ["axios", "request", "unirest", "native", "jquery"],
            },
            // SEO + social preview metadata
            metaData: {
                title: "Kangwifi APIs — Documentation",
                description: "REST API collection with 142 endpoints. Built on Elysia + Bun. Free, no API key required.",
                ogTitle: "Kangwifi APIs",
                ogDescription: "REST API collection with 142 endpoints. Built on Elysia + Bun.",
                ogImage: "https://opengraph.githubassets.com/1/Yz776/apis",
                twitterCard: "summary_large_image",
                twitterTitle: "Kangwifi APIs",
                twitterDescription: "REST API collection with 142 endpoints.",
            },
            // NOTE: customCss is intentionally omitted. The Scalar plugin
            // renders the data-configuration attribute with single quotes,
            // and any apostrophe in the CSS (e.g. "don't" in a comment)
            // breaks the HTML attribute and truncates the JSON, causing a
            // "Unterminated string in JSON" error in the browser console
            // and a blank docs page. The "purple" theme already provides
            // good styling without custom CSS.
        },
        documentation: {
            info: {
                title: "Kangwifi APIs",
                version: "1.0.0",
                description: `# 🚀 Kangwifi APIs

Selamat datang di **Kangwifi APIs** — koleksi **142 REST API endpoint** yang siap pakai, gratis, tanpa API key.

## ✨ Kenapa Pakai API Ini?

- ⚡ **Super cepat** — Dibangun di atas **Bun + Elysia**, response time sub-millisecond
- 🆓 **Gratis & tanpa API key** — Langsung pakai, tidak perlu registrasi
- 📚 **142 endpoint** — AI, downloader, search, tools, Islamic, dan banyak lagi
- 🎯 **Mudah dipakai** — Cukup kirim HTTP request, dapatkan JSON response

## 🎮 Cara Pakai (Pemula)

### 1. Pilih endpoint dari sidebar kiri
Klik salah satu tag (misalnya \`AI\`, \`Downloader\`, \`Search\`) untuk melihat endpoint yang tersedia.

### 2. Klik endpoint untuk melihat detail
Akan muncul: deskripsi, parameter yang dibutuhkan, dan contoh response.

### 3. Klik tombol "Test Request"
Tombol ungu di kanan atas — isi parameter, lalu klik **Send** untuk mencoba endpoint langsung dari browser.

### 4. Atau pakai curl / fetch di kode kamu
Scroll ke bawah endpoint untuk lihat contoh kode siap copy-paste di berbagai bahasa (curl, JavaScript, Python, Go, PHP, dll).

## 📋 Contoh Cepat

\`\`\`bash
# Chat dengan Gemini AI
curl "http://localhost:47291/ai/gemini?prompt=halo"

# Download TikTok video (tanpa watermark)
curl "http://localhost:47291/downloader/tiktokio?url=https://vm.tiktok.com/..."

# Cari di Wikipedia
curl "http://localhost:47291/search/wikipedia?query=indonesia"

# BMKG data gempa terkini
curl "http://localhost:47291/tools/gempa"

# Jadwal sholat Jakarta
curl "http://localhost:47291/islamic/jadwal-sholat?kota=Jakarta"
\`\`\`

## 🏷️ Kategori Endpoint

| Tag | Jumlah | Contoh |
|-----|--------|--------|
| **AI** | 17 | \`/ai/gemini\`, \`/ai/chatgpt\`, \`/ai/mistral\` |
| **Downloader** | 49 | \`/downloader/tiktokio\`, \`/downloader/savetube\`, \`/downloader/instagram\` |
| **Search** | 26 | \`/search/wikipedia\`, \`/search/kbbi\`, \`/search/pinterest\` |
| **Tools** | 47 | \`/tools/qrcode\`, \`/tools/tts\`, \`/tools/shorturl\` |
| **Maker** | 4 | \`/maker/brat\`, \`/maker/qc\` |
| **Islamic** | 6 | \`/islamic/quran-list\`, \`/islamic/jadwal-sholat\` |

## 🔐 Autentikasi

**Tidak perlu API key!** Semua endpoint terbuka untuk umum secara default.

(Jika kamu self-host dan ingin mengaktifkan auth, set \`ENABLE_AUTH=true\` + \`API_KEY=xxx\` di file \`.env\`.)

## 📖 Format Response

Semua endpoint mengembalikan JSON dengan format konsisten:

\`\`\`json
{
  "ok": true,
  "result": { ... },
  "text": "...",
  "error": "..." // hanya saat ok=false
}
\`\`\`

## 🛠️ Stack Teknis

- **Runtime**: [Bun 1.3+](https://bun.sh/) (Zig + JavaScriptCore)
- **Framework**: [ElysiaJS](https://elysiajs.com/)
- **Docs**: [@elysiajs/swagger](https://elysiajs.com/plugins/swagger) (Scalar UI)
- **Source**: [github.com/Yz776/apis](https://github.com/Yz776/apis)

---

## 💡 Tips

- Gunakan **search bar** di sidebar kiri (atau tekan \`Ctrl+K\`) untuk cari endpoint cepat
- Klik tag heading untuk **expand/collapse** semua endpoint di kategori itu
- Setiap endpoint punya **contoh response** di bagian bawah — lihat dulu sebelum pakai
- Kalau endpoint error \`500\`, kemungkinan API upstream sedang down — coba endpoint lain

Selamat bereksplorasi! 🎉`,
            },
            components: {
                securitySchemes: {
                    ApiKeyAuth: {
                        type: "apiKey",
                        in: "header",
                        name: "x-api-key",
                    },
                },
            },
            tags: [
                {
                    name: "AI",
                    description: "🤖 Chat & text generation — Gemini, ChatGPT, Mistral, Qwen, Claude, DeepSeek, Quillbot, dll. Kirim prompt, dapatkan jawaban AI.",
                },
                {
                    name: "Downloader",
                    description: "⬇️ Media downloaders — TikTok, Instagram, YouTube, Spotify, Twitter, Threads, dll. Tanpa watermark.",
                },
                {
                    name: "Search",
                    description: "🔍 Search engines — Wikipedia, KBBI, Tokopedia, Pinterest, YouTube, dll.",
                },
                {
                    name: "Tools",
                    description: "🛠️ Utility tools — QR code, TTS, URL shortener, weather, gempa, translate, dll.",
                },
                {
                    name: "Maker",
                    description: "🎨 Image & text makers — brat generator, quote card, IQC.",
                },
                {
                    name: "Islamic",
                    description: "🕌 Islamic utilities — Quran, jadwal sholat, asmaul husna, doa harian, hadits.",
                },
            ],
        },
    }),
)

// ─── Register every feature route ────────────────────────────────────────────
for (const f of features) {
    const {
        method, path: routePath, auth,
        tags = [], summary, description,
        parameters, requestBody, responses,
    } = f.route

    const verb = method.toLowerCase()
    if (typeof app[verb] !== "function") {
        console.warn(`[skip] unsupported HTTP method "${method}" for ${routePath}`)
        continue
    }

    const handler = adapt(f)

    // Map our route metadata into Elysia's `detail` (for swagger) and
    // `beforeHandle` (for auth check, inlined — no middleware indirection).
    //
    // AUTH: By default `ENABLE_AUTH=false` — the `auth` flag on each feature
    // file is IGNORED and all endpoints are public. Set ENABLE_AUTH=true in
    // .env to enforce `x-api-key` on endpoints marked `auth: true`.
    const enforceAuth = ENABLE_AUTH && auth

    const routeConfig = {
        detail: {
            tags,
            ...(summary && { summary }),
            ...(description && { description }),
            ...(parameters && { params: parameters.filter(p => p.in === "path") }),
            ...(parameters && { query: parameters.filter(p => p.in === "query") }),
            ...(responses && {
                response: Object.fromEntries(
                    Object.entries(responses).map(([code, r]) => [
                        code,
                        r?.content?.["application/json"]?.schema ?? {},
                    ]),
                ),
            }),
            ...(enforceAuth && { security: [{ ApiKeyAuth: [] }] }),
        },
        ...(enforceAuth && {
            beforeHandle: (c) => {
                const key = c.headers["x-api-key"]
                if (!key || key !== API_KEY) {
                    return new Response(
                        JSON.stringify({ ok: false, error: "API key tidak valid" }),
                        { status: 401, headers: { "content-type": "application/json; charset=utf-8" } },
                    )
                }
            },
        }),
    }

    app[verb](routePath, handler, routeConfig)
}

// ─── Root redirect ───────────────────────────────────────────────────────────
app.get("/", () => Response.redirect("/docs", 302))

// ─── 404 / 500 ───────────────────────────────────────────────────────────────
app.onError(({ code, error, path, set }) => {
    if (code === "NOT_FOUND") {
        set.status = 404
        return {
            ok: false,
            error: "Endpoint tidak ditemukan",
            path,
        }
    }
    set.status = 500
    return {
        ok: false,
        error: error?.message || String(error),
        code,
    }
})

// ─── Boot ────────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
    console.log("")
    console.log("  Kangwifi APIs  →  Elysia + Bun edition")
    console.log(`  Listen         →  http://localhost:${PORT}`)
    console.log(`  Docs (Swagger) →  http://localhost:${PORT}/docs`)
    console.log(`  Routes         →  ${features.length}`)
    console.log("")
})
